import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import {
  Activity,
  AlertTriangle,
  CalendarDays,
  Droplets,
  Flame,
  Globe2,
  Hospital,
  Languages,
  Navigation,
  Pill,
  PhoneCall,
  ShieldAlert,
  Siren,
  Stethoscope,
  UserRound,
} from "lucide-react";
import { Logo } from "@/components/brand/logo";
import { Button } from "@/components/ui/button";
import { NOT_PROVIDED, resqrSummaryQuery } from "@/lib/resqr";

export const Route = createFileRoute("/r/$code")({
  head: () => ({
    meta: [
      { title: "Emergency summary — RESQORA RESQR ID" },
      {
        name: "description",
        content:
          "Scanned RESQR ID emergency summary: blood group, allergies, medications, conditions and guardian contact for first responders.",
      },
      { property: "og:title", content: "Emergency summary — RESQORA RESQR ID" },
      {
        property: "og:description",
        content: "Essential emergency details for responders, retrieved from a secure RESQR ID.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
      { name: "robots", content: "noindex,nofollow" },
    ],
  }),
  component: EmergencySummaryPage,
});

function value(input: string | number | null | undefined) {
  if (input === null || input === undefined) return NOT_PROVIDED;
  const text = String(input).trim();
  return text.length > 0 ? text : NOT_PROVIDED;
}

function traumaHospitalLink(preferred: string | null) {
  const query = preferred?.trim()
    ? encodeURIComponent(preferred.trim())
    : encodeURIComponent("trauma centre hospital emergency");
  return `https://www.google.com/maps/search/?api=1&query=${query}`;
}

function EmergencySummaryPage() {
  const { code } = Route.useParams();
  // Refresh while scanned so a responder sees the live SOS state change.
  const summary = useQuery({ ...resqrSummaryQuery(code), refetchInterval: 10_000 });
  const data = summary.data ?? null;
  const live = data?.active_emergency ?? null;

  return (
    <main className="mx-auto w-full max-w-xl px-4 py-6 sm:py-10">
      <header className="flex items-center justify-between gap-3">
        <Logo />
        <span className="rounded-full bg-primary/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-primary">
          RESQR ID
        </span>
      </header>

      {summary.isPending ? (
        <div className="mt-6 h-64 animate-pulse rounded-3xl bg-muted" aria-hidden="true" />
      ) : !data ? (
        <section className="mt-6 rounded-3xl border border-destructive/40 bg-destructive/10 p-6 text-center">
          <ShieldAlert className="mx-auto size-8 text-destructive" aria-hidden="true" />
          <h1 className="mt-3 text-xl font-semibold text-foreground">This RESQR ID is not valid</h1>
          <p className="mt-2 text-sm text-muted-foreground">
            The code may have been regenerated by its owner. Ask them for their current RESQR ID.
          </p>
        </section>
      ) : (
        <>
          {live && (
            <section className="mt-6 rounded-3xl border border-destructive/50 bg-destructive/10 p-5">
              <p className="inline-flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-destructive">
                <Siren className="size-3.5" aria-hidden="true" />
                SOS active now
              </p>
              <h2 className="mt-2 text-lg font-semibold text-foreground">
                {live.reference} · {live.type.replace(/_/g, " ")} · {live.severity}
              </h2>
              <p className="mt-1 text-sm text-muted-foreground">
                {live.address ?? "Location resolving…"} · started{" "}
                {new Date(live.started_at).toLocaleTimeString()}
                {live.location_updated_at
                  ? ` · location updated ${new Date(live.location_updated_at).toLocaleTimeString()}`
                  : ""}
              </p>
              {live.latitude != null && live.longitude != null && (
                <Button
                  asChild
                  size="lg"
                  variant="destructive"
                  className="mt-3 h-14 w-full justify-start rounded-2xl text-base"
                >
                  <a
                    href={`https://www.google.com/maps/dir/?api=1&destination=${live.latitude},${live.longitude}&travelmode=driving`}
                    target="_blank"
                    rel="noreferrer"
                  >
                    <Navigation className="size-5" aria-hidden="true" />
                    Navigate to their live location
                  </a>
                </Button>
              )}
            </section>
          )}

          <section className="mt-6 rounded-3xl border border-border bg-card p-5 shadow-sm">
            <h1 className="text-lg font-semibold text-foreground">Emergency summary</h1>
            <p className="mt-1 text-sm text-muted-foreground">
              Essential care details only. No addresses, accounts or identity documents.
            </p>

            <dl className="mt-5 divide-y divide-border">
              <Row icon={UserRound} label="Name" text={value(data.full_name)} emphasis />
              <Row icon={Droplets} label="Blood group" text={value(data.blood_group)} emphasis />
              <Row icon={CalendarDays} label="Age" text={value(data.age)} />
              <Row icon={AlertTriangle} label="Allergies" text={value(data.allergies)} />
              <Row icon={Pill} label="Current medicines" text={value(data.medications)} />
              <Row
                icon={Stethoscope}
                label="Medical conditions"
                text={value(data.medical_conditions)}
              />
              <Row icon={PhoneCall} label="Guardian name" text={value(data.guardian_name)} />
              <Row icon={PhoneCall} label="Guardian phone" text={value(data.guardian_phone)} />
              <Row
                icon={Hospital}
                label="Preferred hospital"
                text={value(data.preferred_hospital)}
              />
              <Row
                icon={Languages}
                label="Preferred language"
                text={value(data.preferred_language)}
              />
            </dl>
          </section>

          <section className="mt-4 space-y-3">
            <h2 className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
              Quick emergency actions
            </h2>
            <Button
              asChild
              size="lg"
              className="h-16 w-full justify-start rounded-2xl text-base"
              disabled={!data.guardian_phone}
            >
              <a href={`tel:${(data.guardian_phone ?? "").replace(/[^\d+]/g, "")}`}>
                <PhoneCall className="size-5" aria-hidden="true" />
                Call guardian{data.guardian_name ? ` — ${data.guardian_name}` : ""}
              </a>
            </Button>
            <Button
              asChild
              size="lg"
              variant="destructive"
              className="h-16 w-full justify-start rounded-2xl text-base"
            >
              <a href="tel:108">
                <Siren className="size-5" aria-hidden="true" />
                Call ambulance (108)
              </a>
            </Button>
            <Button
              asChild
              size="lg"
              variant="outline"
              className="h-16 w-full justify-start rounded-2xl text-base"
            >
              <a href="tel:112">
                <Activity className="size-5" aria-hidden="true" />
                Call police (112)
              </a>
            </Button>
            <Button
              asChild
              size="lg"
              variant="outline"
              className="h-16 w-full justify-start rounded-2xl text-base"
            >
              <a
                href={traumaHospitalLink(data.preferred_hospital)}
                target="_blank"
                rel="noreferrer"
              >
                <Navigation className="size-5" aria-hidden="true" />
                Navigate to nearest trauma hospital
              </a>
            </Button>
          </section>

          <p className="mt-5 flex items-start gap-2 rounded-2xl bg-muted/60 px-4 py-3 text-xs text-muted-foreground">
            <Flame className="mt-0.5 size-3.5 shrink-0" aria-hidden="true" />
            For life-threatening situations call emergency services immediately. These details are
            self-reported by the RESQORA user and are not a medical diagnosis.
          </p>
          <p className="mt-3 flex items-center justify-center gap-2 text-[11px] text-muted-foreground">
            <Globe2 className="size-3.5" aria-hidden="true" />
            Retrieved securely with a RESQR ID — no personal data is stored in the QR code.
          </p>
        </>
      )}
    </main>
  );
}

function Row({
  icon: Icon,
  label,
  text,
  emphasis,
}: {
  icon: typeof UserRound;
  label: string;
  text: string;
  emphasis?: boolean;
}) {
  return (
    <div className="flex items-start justify-between gap-4 py-3">
      <dt className="flex items-center gap-2 text-sm text-muted-foreground">
        <Icon className="size-4 shrink-0" aria-hidden="true" />
        {label}
      </dt>
      <dd
        className={
          emphasis
            ? "text-right text-base font-semibold text-foreground"
            : "text-right text-sm font-medium text-foreground"
        }
      >
        {text}
      </dd>
    </div>
  );
}
