/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAssistantRouteImport } from './routes/_app.assistant'
import { Route as AppCheckinsRouteImport } from './routes/_app.checkins'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppCoreRouteImport } from './routes/_app.core'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDigitalTwinRouteImport } from './routes/_app.digital-twin'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDonorsRouteImport } from './routes/_app.donors'
import { Route as AppEmailDiagnosticsRouteImport } from './routes/_app.email-diagnostics'
import { Route as AppEmergencyRouteImport } from './routes/_app.emergency'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppLiveRouteImport } from './routes/_app.live'
import { Route as AppMedaiRouteImport } from './routes/_app.medai'
import { Route as AppMedicalIdRouteImport } from './routes/_app.medical-id'
import { Route as AppNearbyRouteImport } from './routes/_app.nearby'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppResqAiRouteImport } from './routes/_app.resq-ai'
import { Route as AppResqrIdRouteImport } from './routes/_app.resqr-id'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppShareCenterRouteImport } from './routes/_app.share-center'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as MTokenRouteImport } from './routes/m.$token'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ApiPublicPushConfigRouteImport } from './routes/api/public/push-config'
import { Route as GuardianEmergencyIdTokenRouteImport } from './routes/guardian.$emergencyId.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinsRoute = AppCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCoreRoute = AppCoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDigitalTwinRoute = AppDigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDonorsRoute = AppDonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailDiagnosticsRoute = AppEmailDiagnosticsRouteImport.update({
  id: '/email-diagnostics',
  path: '/email-diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppMedaiRoute = AppMedaiRouteImport.update({
  id: '/medai',
  path: '/medai',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalIdRoute = AppMedicalIdRouteImport.update({
  id: '/medical-id',
  path: '/medical-id',
  getParentRoute: () => AppRoute,
} as any)
const AppNearbyRoute = AppNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppResqAiRoute = AppResqAiRouteImport.update({
  id: '/resq-ai',
  path: '/resq-ai',
  getParentRoute: () => AppRoute,
} as any)
const AppResqrIdRoute = AppResqrIdRouteImport.update({
  id: '/resqr-id',
  path: '/resqr-id',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShareCenterRoute = AppShareCenterRouteImport.update({
  id: '/share-center',
  path: '/share-center',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const MTokenRoute = MTokenRouteImport.update({
  id: '/m/$token',
  path: '/m/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushConfigRoute = ApiPublicPushConfigRouteImport.update({
  id: '/api/public/push-config',
  path: '/api/public/push-config',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianEmergencyIdTokenRoute =
  GuardianEmergencyIdTokenRouteImport.update({
    id: '/guardian/$emergencyId/$token',
    path: '/guardian/$emergencyId/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRoute
  '/assistant': typeof AppAssistantRoute
  '/checkins': typeof AppCheckinsRoute
  '/contacts': typeof AppContactsRoute
  '/core': typeof AppCoreRoute
  '/dashboard': typeof AppDashboardRoute
  '/digital-twin': typeof AppDigitalTwinRoute
  '/documents': typeof AppDocumentsRoute
  '/donors': typeof AppDonorsRoute
  '/email-diagnostics': typeof AppEmailDiagnosticsRoute
  '/emergency': typeof AppEmergencyRoute
  '/history': typeof AppHistoryRoute
  '/live': typeof AppLiveRoute
  '/medai': typeof AppMedaiRoute
  '/medical-id': typeof AppMedicalIdRoute
  '/nearby': typeof AppNearbyRoute
  '/notes': typeof AppNotesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/report': typeof AppReportRoute
  '/resq-ai': typeof AppResqAiRoute
  '/resqr-id': typeof AppResqrIdRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/share-center': typeof AppShareCenterRoute
  '/support': typeof AppSupportRoute
  '/m/$token': typeof MTokenRoute
  '/r/$code': typeof RCodeRoute
  '/s/$token': typeof STokenRoute
  '/api/public/push-config': typeof ApiPublicPushConfigRoute
  '/guardian/$emergencyId/$token': typeof GuardianEmergencyIdTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRoute
  '/assistant': typeof AppAssistantRoute
  '/checkins': typeof AppCheckinsRoute
  '/contacts': typeof AppContactsRoute
  '/core': typeof AppCoreRoute
  '/dashboard': typeof AppDashboardRoute
  '/digital-twin': typeof AppDigitalTwinRoute
  '/documents': typeof AppDocumentsRoute
  '/donors': typeof AppDonorsRoute
  '/email-diagnostics': typeof AppEmailDiagnosticsRoute
  '/emergency': typeof AppEmergencyRoute
  '/history': typeof AppHistoryRoute
  '/live': typeof AppLiveRoute
  '/medai': typeof AppMedaiRoute
  '/medical-id': typeof AppMedicalIdRoute
  '/nearby': typeof AppNearbyRoute
  '/notes': typeof AppNotesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/report': typeof AppReportRoute
  '/resq-ai': typeof AppResqAiRoute
  '/resqr-id': typeof AppResqrIdRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/share-center': typeof AppShareCenterRoute
  '/support': typeof AppSupportRoute
  '/m/$token': typeof MTokenRoute
  '/r/$code': typeof RCodeRoute
  '/s/$token': typeof STokenRoute
  '/api/public/push-config': typeof ApiPublicPushConfigRoute
  '/guardian/$emergencyId/$token': typeof GuardianEmergencyIdTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/checkins': typeof AppCheckinsRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/core': typeof AppCoreRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/digital-twin': typeof AppDigitalTwinRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/donors': typeof AppDonorsRoute
  '/_app/email-diagnostics': typeof AppEmailDiagnosticsRoute
  '/_app/emergency': typeof AppEmergencyRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/live': typeof AppLiveRoute
  '/_app/medai': typeof AppMedaiRoute
  '/_app/medical-id': typeof AppMedicalIdRoute
  '/_app/nearby': typeof AppNearbyRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/report': typeof AppReportRoute
  '/_app/resq-ai': typeof AppResqAiRoute
  '/_app/resqr-id': typeof AppResqrIdRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/share-center': typeof AppShareCenterRoute
  '/_app/support': typeof AppSupportRoute
  '/m/$token': typeof MTokenRoute
  '/r/$code': typeof RCodeRoute
  '/s/$token': typeof STokenRoute
  '/api/public/push-config': typeof ApiPublicPushConfigRoute
  '/guardian/$emergencyId/$token': typeof GuardianEmergencyIdTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/activity'
    | '/admin'
    | '/assistant'
    | '/checkins'
    | '/contacts'
    | '/core'
    | '/dashboard'
    | '/digital-twin'
    | '/documents'
    | '/donors'
    | '/email-diagnostics'
    | '/emergency'
    | '/history'
    | '/live'
    | '/medai'
    | '/medical-id'
    | '/nearby'
    | '/notes'
    | '/notifications'
    | '/profile'
    | '/report'
    | '/resq-ai'
    | '/resqr-id'
    | '/scan'
    | '/settings'
    | '/share-center'
    | '/support'
    | '/m/$token'
    | '/r/$code'
    | '/s/$token'
    | '/api/public/push-config'
    | '/guardian/$emergencyId/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/activity'
    | '/admin'
    | '/assistant'
    | '/checkins'
    | '/contacts'
    | '/core'
    | '/dashboard'
    | '/digital-twin'
    | '/documents'
    | '/donors'
    | '/email-diagnostics'
    | '/emergency'
    | '/history'
    | '/live'
    | '/medai'
    | '/medical-id'
    | '/nearby'
    | '/notes'
    | '/notifications'
    | '/profile'
    | '/report'
    | '/resq-ai'
    | '/resqr-id'
    | '/scan'
    | '/settings'
    | '/share-center'
    | '/support'
    | '/m/$token'
    | '/r/$code'
    | '/s/$token'
    | '/api/public/push-config'
    | '/guardian/$emergencyId/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/_app/activity'
    | '/_app/admin'
    | '/_app/assistant'
    | '/_app/checkins'
    | '/_app/contacts'
    | '/_app/core'
    | '/_app/dashboard'
    | '/_app/digital-twin'
    | '/_app/documents'
    | '/_app/donors'
    | '/_app/email-diagnostics'
    | '/_app/emergency'
    | '/_app/history'
    | '/_app/live'
    | '/_app/medai'
    | '/_app/medical-id'
    | '/_app/nearby'
    | '/_app/notes'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/report'
    | '/_app/resq-ai'
    | '/_app/resqr-id'
    | '/_app/scan'
    | '/_app/settings'
    | '/_app/share-center'
    | '/_app/support'
    | '/m/$token'
    | '/r/$code'
    | '/s/$token'
    | '/api/public/push-config'
    | '/guardian/$emergencyId/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  MTokenRoute: typeof MTokenRoute
  RCodeRoute: typeof RCodeRoute
  STokenRoute: typeof STokenRoute
  ApiPublicPushConfigRoute: typeof ApiPublicPushConfigRoute
  GuardianEmergencyIdTokenRoute: typeof GuardianEmergencyIdTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkins': {
      id: '/_app/checkins'
      path: '/checkins'
      fullPath: '/checkins'
      preLoaderRoute: typeof AppCheckinsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/core': {
      id: '/_app/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof AppCoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/digital-twin': {
      id: '/_app/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof AppDigitalTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/donors': {
      id: '/_app/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof AppDonorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email-diagnostics': {
      id: '/_app/email-diagnostics'
      path: '/email-diagnostics'
      fullPath: '/email-diagnostics'
      preLoaderRoute: typeof AppEmailDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emergency': {
      id: '/_app/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medai': {
      id: '/_app/medai'
      path: '/medai'
      fullPath: '/medai'
      preLoaderRoute: typeof AppMedaiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical-id': {
      id: '/_app/medical-id'
      path: '/medical-id'
      fullPath: '/medical-id'
      preLoaderRoute: typeof AppMedicalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nearby': {
      id: '/_app/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof AppNearbyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resq-ai': {
      id: '/_app/resq-ai'
      path: '/resq-ai'
      fullPath: '/resq-ai'
      preLoaderRoute: typeof AppResqAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resqr-id': {
      id: '/_app/resqr-id'
      path: '/resqr-id'
      fullPath: '/resqr-id'
      preLoaderRoute: typeof AppResqrIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/share-center': {
      id: '/_app/share-center'
      path: '/share-center'
      fullPath: '/share-center'
      preLoaderRoute: typeof AppShareCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/m/$token': {
      id: '/m/$token'
      path: '/m/$token'
      fullPath: '/m/$token'
      preLoaderRoute: typeof MTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-config': {
      id: '/api/public/push-config'
      path: '/api/public/push-config'
      fullPath: '/api/public/push-config'
      preLoaderRoute: typeof ApiPublicPushConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/$emergencyId/$token': {
      id: '/guardian/$emergencyId/$token'
      path: '/guardian/$emergencyId/$token'
      fullPath: '/guardian/$emergencyId/$token'
      preLoaderRoute: typeof GuardianEmergencyIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCheckinsRoute: typeof AppCheckinsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppCoreRoute: typeof AppCoreRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDigitalTwinRoute: typeof AppDigitalTwinRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppDonorsRoute: typeof AppDonorsRoute
  AppEmailDiagnosticsRoute: typeof AppEmailDiagnosticsRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLiveRoute: typeof AppLiveRoute
  AppMedaiRoute: typeof AppMedaiRoute
  AppMedicalIdRoute: typeof AppMedicalIdRoute
  AppNearbyRoute: typeof AppNearbyRoute
  AppNotesRoute: typeof AppNotesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportRoute: typeof AppReportRoute
  AppResqAiRoute: typeof AppResqAiRoute
  AppResqrIdRoute: typeof AppResqrIdRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShareCenterRoute: typeof AppShareCenterRoute
  AppSupportRoute: typeof AppSupportRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAdminRoute: AppAdminRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCheckinsRoute: AppCheckinsRoute,
  AppContactsRoute: AppContactsRoute,
  AppCoreRoute: AppCoreRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDigitalTwinRoute: AppDigitalTwinRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppDonorsRoute: AppDonorsRoute,
  AppEmailDiagnosticsRoute: AppEmailDiagnosticsRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLiveRoute: AppLiveRoute,
  AppMedaiRoute: AppMedaiRoute,
  AppMedicalIdRoute: AppMedicalIdRoute,
  AppNearbyRoute: AppNearbyRoute,
  AppNotesRoute: AppNotesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportRoute: AppReportRoute,
  AppResqAiRoute: AppResqAiRoute,
  AppResqrIdRoute: AppResqrIdRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShareCenterRoute: AppShareCenterRoute,
  AppSupportRoute: AppSupportRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  MTokenRoute: MTokenRoute,
  RCodeRoute: RCodeRoute,
  STokenRoute: STokenRoute,
  ApiPublicPushConfigRoute: ApiPublicPushConfigRoute,
  GuardianEmergencyIdTokenRoute: GuardianEmergencyIdTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
